version: "3.9"

services:
  db:
    image: postgres
    restart: always

    environment:
      POSTGRES_DB: tsu_toleg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5436:5432"
  app:
    image: app
    restart: on-failure
    ports:
      - "7000:7000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads

volumes:
  dbdata: