version: '3.9'

services:
  my_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tsu-toleg
    container_name: tsu_toleg_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tsu_toleg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d storage -U test" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge