// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {
            "name": "Gadam Jumayev",
            "url": "https://github.com/jumayevgadam",
            "email": "hypergadam@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/faculty/create": {
            "post": {
                "description": "Creates a new faculty and returns its id.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Faculties"
                ],
                "summary": "Add a new faculty.",
                "operationId": "add-faculty",
                "parameters": [
                    {
                        "type": "string",
                        "name": "faculty-code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "faculty-name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/faculty/get-all": {
            "get": {
                "description": "list faculties, pagination not setted.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Faculties"
                ],
                "summary": "List faculties.",
                "operationId": "list-faculties",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_jumayevgadam_tsu-toleg_internal_models_faculty.Faculty"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/faculty/{id}": {
            "get": {
                "description": "retrieve faculty using its id.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Faculties"
                ],
                "summary": "get-faculty.",
                "operationId": "get-faculty",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jumayevgadam_tsu-toleg_internal_models_faculty.Faculty"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "put": {
                "description": "update faculty fields using identified faculty id",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Faculties"
                ],
                "summary": "Update Faculty",
                "operationId": "update-faculty",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "needed faculty id for update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "faculty-code",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "faculty-name",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully updated faculty ops",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "delete faculty using identified id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Faculties"
                ],
                "summary": "delete-faculty",
                "operationId": "delete-faculty",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully deleted faculty",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/group/add": {
            "post": {
                "description": "Creates a new group and returns its id.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Add a new group.",
                "operationId": "add-group",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "faculty-id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "group-code",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/group/get-all": {
            "get": {
                "description": "Listing groups by pagination.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "List groups.",
                "operationId": "list-group",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "page",
                        "description": "page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "limit",
                        "description": "number of elements per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "orderBy",
                        "description": "filter name",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_jumayevgadam_tsu-toleg_internal_models_group.GroupDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        },
        "/group/{id}": {
            "get": {
                "description": "Retrieve a group using by identified id.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Get one group by its id.",
                "operationId": "get-group",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_jumayevgadam_tsu-toleg_internal_models_group.GroupDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "put": {
                "description": "update a group details using their fields.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Update a group.",
                "operationId": "update-group",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "needed group id for update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "faculty-id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "name": "group-code",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated group",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            },
            "delete": {
                "description": "Delete group by id",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "Delete group.",
                "operationId": "delete-group",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {}
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {}
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_jumayevgadam_tsu-toleg_internal_models_faculty.Faculty": {
            "type": "object",
            "required": [
                "faculty-code",
                "facultyName"
            ],
            "properties": {
                "faculty-code": {
                    "type": "string"
                },
                "facultyID": {
                    "type": "integer"
                },
                "facultyName": {
                    "type": "string"
                }
            }
        },
        "github_com_jumayevgadam_tsu-toleg_internal_models_group.GroupDTO": {
            "type": "object",
            "properties": {
                "classCode": {
                    "type": "string"
                },
                "facultyID": {
                    "type": "integer"
                },
                "groupID": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:5000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "TSU-TOLEG API Documentation",
	Description:      "This is the API for the TSU-TOLEG system.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
